version: "3.9"
   
services:
  backend:
    build: ./backend
    command: bash -c "python manage.py runserver 0.0.0.0:8000 && celery -A proj worker -B" 
    volumes:
      - ./backend:/code
    ports:
      - "8000:8000"
    depends_on:
      - redis

  frontend:
    image: ebiven/vue-cli
    command: bash -c "npm install && npm run serve"
    volumes:
      - ./frontend:/code
    ports:
      - "8080:8080"
  redis:
    image: 'redis'
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - '6379:6379'
    volumes:
      - 'redis_data:/data' 

volumes:
  redis_data:
    driver: local