# Generated by Django 3.1 on 2020-10-12 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notepad', '0003_auto_20201009_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='file',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='note',
            name='delete_after_viewing',
            field=models.BooleanField(default=False),
        ),
    ]
