# Generated by Django 3.1 on 2020-10-12 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notepad', '0005_auto_20201012_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='code',
            field=models.TextField(default=None, null=True),
        ),
    ]
