# Generated by Django 3.1 on 2020-11-05 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notepad', '0009_remove_note_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='highlighted',
        ),
        migrations.RemoveField(
            model_name='note',
            name='linenos',
        ),
        migrations.AlterField(
            model_name='note',
            name='code',
            field=models.TextField(blank=True, default='', max_length=65536),
        ),
    ]
