# Generated by Django 3.1 on 2020-11-16 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notepad', '0010_auto_20201105_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='delete_time',
            field=models.DateTimeField(default=None),
        ),
    ]
