# Generated by Django 3.1 on 2021-07-07 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subscription',
            field=models.TextField(choices=[('B', 'Basic'), ('P', 'Premium'), ('U', 'Unlimited')], default='B'),
        ),
    ]
