# Generated by Django 3.1 on 2020-10-12 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notepad', '0004_auto_20201012_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='code',
            field=models.TextField(null=True),
        ),
    ]
