# Generated by Django 3.1 on 2020-10-17 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notepad', '0007_auto_20201012_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='code',
            field=models.TextField(blank=True, default=None, max_length=65536),
        ),
    ]
